version: '2'
services:
  web:
    build: .
    volumes:
      - ./:/jwtauth
      - /jwtauth/node_modules
    ports:
      - "80:3000"
    restart: always
    links: ["mongo"]
  mongo:
    container_name: mongo
    image: mongo:3.6.2
    restart: always
    ports: ["27017:27017"]
  mongoclient:
      image: mongoclient/mongoclient
      depends_on:
        - mongo
      ports: ["3300:3000"]
